version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre_build:
    commands:
      - yum -y install yum-utils
      - echo Installing sqlite
      - yum -y install sqlite
      - echo Installing ruby on rails...
      - gem update --system
      - gem install bundler
      - bundle install
  build:
    commands:
      - rails db:migrate RAILS_ENV=test
      - rails test
