version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
#  pre_build:
#    commands:
#      - echo Installing sqlite
#      - yum -y install sqlite
#      - echo Installing ruby on rails...
#      - gem update --system
#      - gem install bundler -v 1.17.3
#      - bundle install
#  build:
#    commands:
#      - bin/rails db:migrate RAILS_ENV=test
#      - bin/rails test
  post_build:
    commands:
      - pwd
      - tar cvzf aws-intro-sample.tgz Gemfile Gemfile.lock Rakefile app bin config config.ru db lib log package.json public test tmp vendor
      - ls
      - aws s3 cp aws-intro-sample.tgz s3://aws-intro-sample-deploy/
