version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre-build:
    commands:
      - yum install mysql-server
      - gem update --system
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
  build:
    commands:
      - rails test
